// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetGram.Data;

namespace NetGram.Migrations
{
    [DbContext(typeof(GramDbcontext))]
    [Migration("20190213192435_seeded")]
    partial class seeded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NetGram.Models.Gram", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("Title");

                    b.Property<string>("URL");

                    b.HasKey("ID");

                    b.ToTable("Gram");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Bill",
                            Title = "LOLOLOL",
                            URL = ".png"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Sam",
                            Title = "This dog!",
                            URL = ".png"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Joe",
                            Title = "This is Seattle",
                            URL = ".png"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Kat",
                            Title = ":)",
                            URL = ".png"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Mat",
                            Title = "I love this pizza",
                            URL = ".png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
